spring:
  application:
    name: KEYCLOAK-SERVICE
  config:
    import: optional:configserver:http://localhost:9000
  management:
    endpoints:
      web:
        exposure:
          include: health, info, metrics

